name: JSON Project Workflow with Email Notification

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq (JSON processor)
        run: sudo apt-get install -y jq

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install JSON npm packages
        run: |
          npm install -g json
          npm install -g jsonlint

      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.google.com
          port: 465
          account: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.MAIL_PASSWORD }}
          sender: Power BI Reports
          from: ${{ secrets.MAIL_ADDRESS }}
          to: ganabal.82704@gmail.com
          subject: Power BI Reports - Main Branch Update
          body: |
            The main branch of the Power BI reports repository has been updated.
            Please review the latest changes.
          contentType: text/plain
          attachments: '[{"path":"README.md"}]'
