name: JSON Project Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq (JSON processor)
        run: sudo apt-get install -y jq

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install JSON npm packages
        run: |
          npm install -g json
          npm install -g jsonlint

      - name: Push main branch into production
        uses: codingforentrepreneurs/action-branch-to-branch@main
        with:
          dest_branch: 'production-v1'
          source_branch: 'main'
          commit_message: 'Release production version'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET }}
          

